/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AircraftCrewRole;

import Business.Airline.AircraftCrew;
import Business.Airline.Airline;
import Business.Airline.Flight;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class AircraftCrewWorkAreaJPanel extends javax.swing.JPanel {

    JPanel mainScreen;
    EcoSystem system;
    UserAccount userAccount;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public AircraftCrewWorkAreaJPanel(JPanel mainScreen, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.mainScreen = mainScreen;
        this.userAccount = userAccount;
        this.system = system;
        populatetblFlt();
        System.out.println(userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblFlt = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(104, 139, 241));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFlt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight_id", "Original Place", "Destination Place", "Departure time", "Arriving time", "Airplane_id.", "Cost", "Airline Company"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblFlt);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 310));

        btnAssign.setBackground(new java.awt.Color(183, 193, 246));
        btnAssign.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(238, 238, 238));
        btnAssign.setText("Assign to me");
        btnAssign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 170, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirlineImages/icons8-crew-100-2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 110, 100));

        jPanel1.setBackground(new java.awt.Color(183, 193, 246));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 280, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlt.getSelectedRow();
        for(Airline al : system.getAirlineDirectory().getAirlineList()){
            for(AircraftCrew ac : al.getAircraftcrewList()){
                if(ac.getName().equals(userAccount.getName())){
                    if(selectedRow>=0){
                        ac.setStatus("Working");
                        for(Flight fl : al.getFlightList()){
                            if(fl.getFlight_id().equals((String) tblFlt.getValueAt(selectedRow, 0))){
                                fl.setReadyStatus(true);
                                ac.setFlight(fl.getFlight_id());
                                JOptionPane.showMessageDialog(this,"The Aircraft Cerw is ready.");
                            }
                        }
                    }else{
                        JOptionPane.showMessageDialog(this,"Please select a row.");
                    }
                }
            }
        }

    }//GEN-LAST:event_btnAssignActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblFlt;
    // End of variables declaration//GEN-END:variables

    private void populatetblFlt() {
        DefaultTableModel model = (DefaultTableModel) tblFlt.getModel();
        model.setRowCount(0);
        for (Airline al : system.getAirlineDirectory().getAirlineList()) {
            for(Flight fl : al.getFlightList()){
                if(fl.getAirplane_id() != null && fl.isStatus()==false){
                    Object[] row = new Object[8];
                    row[0] = fl.getFlight_id();
                    row[1] = fl.getOriginalplace();
                    row[2] = fl.getDestinationplace();
                    row[3] = fl.getDepartureTime();
                    row[4] = fl.getArrivingTime();
                    row[5] = fl.getAirplane_id();
                    row[6] = fl.getCost();
                    row[7] = al.getName();
                    model.addRow(row);
                }
            }
        }
    }
}
